language: python

python:
    - 3.6

before_install:
  - echo "START"
  # install dependencies
  - pip install -r requirements.txt

before_script:
#  - chmod +x start.sh
#  - chmod +x run_worker.sh

install:
    - gunicorn manage:app

script:
    - pytest  # run tests
#    # TODO start celery worker
#    - gunicorn manage:app  # TODO use shell script for this

# blacklist
branches:
  except:
    - legacy
    - dev

# whitelist
branches:
  only:
    - master
    - stable

notifications:
  email:
    - npiusdan@gmail.com
  on_success: change
  on_failure: always